name: Publish

on:
  pull_request:
    branches:
      - main

jobs:
  test_package:
    name: Test React package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.x"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run pytest
        run: |
          pytest